# Generated by Django 5.0.6 on 2024-06-13 09:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yonalish nomi')),
                ('description', models.TextField(verbose_name='Yonalishlar haqida malumot')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='yuborilgan vaqt')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='kurs nomi')),
                ('duration', models.CharField(max_length=50, verbose_name='Davomiyligi')),
                ('description', models.TextField(verbose_name='curs haqida malumot')),
                ('beginning', models.DateField(verbose_name='Boshlash vaqti')),
                ('ending', models.DateField(blank=True, null=True, verbose_name='tugatilgan vaqt')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="kim tomonidan qo'shilgani")),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Dars mavzusi')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='dars yuklangan vaqti')),
                ('update', models.DateTimeField(auto_now=True, verbose_name="Darsga o'zgartirish kiritilgan vaqti")),
                ('independent_work', models.FileField(blank=True, null=True, upload_to='lesson/independent_work/', verbose_name='mustaqil ishlar uchun')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='course.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Matn')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='kim yozgani')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course.lesson', verbose_name='qaysi dars uchun')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.BooleanField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='Rasimi')),
                ('phone', models.CharField(max_length=13, verbose_name='Telfon raqami')),
                ('address', models.CharField(max_length=100, verbose_name='Yashash joyi')),
                ('experience', models.CharField(max_length=50, verbose_name='ish tajribasi')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='course.teacher'),
        ),
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='lesson/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wmv'])])),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='course.lesson')),
            ],
        ),
    ]
