# Generated by Django 5.0.6 on 2024-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='ending',
            field=models.DateField(blank=True, null=True, verbose_name='tugaydigan vaqt'),
        ),
    ]
